### ISSUE TITLE
Hi I want to wish my sister happy birthday!

### ISSUE THREAD

**Issue by codepool20** [kanakagrawal54/Happy-Birthday#1]
I would be grateful if you may help me setup the GitHub page for it 😄

**Comment by kanakagrawal54** [comment]
Hello, I will be happy to help you ... 
All you need is to fork this repository.. and then 
After doing the required changes.. you can go on setting of your repository and there will be option named pages..choose it  ..in ssource section select master branch and click save .. this will provide you a link to open this webpage ..you can also custom the link in below available section ..which you can share with your sister..

**Comment by codepool20** [comment]
thanks I am able to make one
